---
title: "ETFproject"
output: html_document
---
rm(list = ls())

## dinamic websites

lets gather the website as html throuth jsp 
#scrape_techstars.js

#https://www.datacamp.com/community/tutorials/scraping-javascript-generated-data-with-r#gs.er=B0wg

```{js  pressure, echo=FALSE}


var args = require('system').args;
var webPage = require('webpage');
var page = webPage.create();

var fs = require('fs');

var address = args[1];
var path = args[2];

page.open(address, function (status) {
  var content = page.content;
  fs.write("etfs_" + path + ".html",content,'w')
  phantom.exit();
});

```

## dinamic websites

```{r  pressure, echo=FALSE}

setwd("/Users/davidmonteagudo/git/")
setwd("D:/repos/BlogsEntries/Scraping/")


url =  "http://etfdb.com/type/sector/all/#etfs__overview&sort_name=assets_under_management&sort_order=desc&page="


for (i in 1:3) {system(sprintf("./phantomjs-2.1.1-macosx/bin/phantomjs ./Scraping/blog/scrape_etf.js %s%d %d" , url, i, i))}

system("D:/repos/BlogsEntries/Scraping/htmldata/phantomjs/phantomjs.exe")
for (i in 1:3) {system(sprintf("./htmldata/phantomjs/phantomjs.exe ./blog/scrape_etf.js %s%d %d" , url, i, i))}

```





```{r htmltable, echo=FALSE}

###### Settings
library(XML)
 
 
###### Reading data

macurl <-  "/Users/davidmonteagudo/git/Scraping/techstars.xml"
winUrl  <-  "D:/repos/BlogsEntries/Scraping/htmldata/etf_1.html"

localurl <- winUrl



# select table nodes of interest



etf<-readHTMLTable(localurl)[[2]]


header = c("Symbol", "Inception")

etf$Symbol[1]


colnames(etf)<-c("Symbol","ETFdb.com Category","Inception")
class(etf)

for (i in 2:len) 	{tbl<-rbind(etf,readHTMLTable(url[i])[[2]])}
 
###### Formatting data
colnames(tbl)<-c("Symbol","ETFdb.com Category","Inception")
tbl$BirthDate<-as.Date(tbl$BirthDate[1],format="%B %d, %Y")

```

```{r htmltable, echo=FALSE}

url <-winUrl
htmltab1 <- htmltab(doc = url,which = 2)
unique(htmltab1$`ETFdb.com Category`)

```
